services:
  app:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: "3000"
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "3000"]
    healthcheck:
      test: ["CMD", "python", "-c", "import os,socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', int(os.getenv('PORT','3000')))); s.close()"]
      interval: 10s
      timeout: 3s
      retries: 5

  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./landing:/srv/www:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      app:
        condition: service_started

  # Optional Mongo (uncomment if you want local Mongo here)
  # mongo:
  #   image: mongo:6
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

volumes:
  caddy_data:
  caddy_config:
  # mongo_data:
